### ISSUE TITLE
[BUG]  using jsonPath in Custom Monitor mode to resolve path containing - unrecognized

### ISSUE THREAD

**Issue by san346596324** [dromara/hertzbeat#1051] opened 2023-06-28 06:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1.docking Flink Interface【http://flink/jobs/overview】returned results 
【
{
	"jobs": [
		{
			"jid": "abbbbbbbbb",
			"name": "aaaaa",
			"state": "RUNNING",
			"start-time": 1687488064772,
			"end-time": -1,
			"duration": 441540547,
			"last-modification": 1687488082063,
			"tasks": {
				"total": 4,
				"created": 0,
				"scheduled": 0,
				"deploying": 0,
				"running": 4,
				"finished": 0,
				"canceling": 0,
				"canceled": 0,
				"failed": 0,
				"reconciling": 0,
				"initializing": 0
			}
		}
	]
}
】
2.The returned result contains the last modification. I want to use jsonpath to obtain parameters for addition and subtraction, but it cannot be recognized. Whether it is # ` $. last modification 'or $. last modification, the result displayed in the foreground is  &nbsp;
![image](https://github.com/dromara/hertzbeat/assets/30828520/7d95e6e1-1b00-42b6-8f4a-5ae36448b7b6)
3.These are some template parameters
【
 - name:  flink_details
    priority: 2
    fields:
      - field: responseTime
        type: 1
      - field: name
        instance: true
        type: 1
      - field: cccaaa
        type: 0
    aliasFields:
      - responseTime
      - $.name
      - $.start-time
      - $.last-modification
    calculates:
      - responseTime = responseTime
      - name =  $.name
      - cccaaa =  #`$.last-modification` - #`$.start-time`
    protocol: http
    http:
      host: ^_^host^_^
      port: ^_^port^_^
      url: /proxy/^_^uri^_^/jobs/overview
      timeout: ^_^timeout^_^
      method: GET
      ssl: ^_^ssl^_^
      authorization:
        type: ^_^authType^_^
        basicAuthUsername: ^_^username^_^
        basicAuthPassword: ^_^password^_^
        digestAuthUsername: ^_^username^_^
        digestAuthPassword: ^_^password^_^
      parseType: jsonPath
      parseScript: '$.jobs.*' 
】
 

### Expected Behavior

Obtain the values of start-time and last-modification for subtraction operation

### Steps To Reproduce

1. flink version:1.5.4
2. Custom Monitor mode request flink Interface【http://flink/jobs/overview】

### Environment

```markdown
HertzBeat version(s):1.3.1
```

### Debug logs

no

### Anything else?

no

**Comment by l646505418** [comment] 2023-06-28 12:31
hi @san346596324  have you ever tried not add `#`, you can reference to th docker template

![docker](https://github.com/dromara/hertzbeat/assets/50475131/79f8925c-5323-42a4-9807-e0ea9eb0c29d)

**Comment by l646505418** [comment] 2023-06-28 12:35
> hi @san346596324 have you ever tried not add `#`, you can reference to th docker template
> 
> ![docker](https://user-images.githubusercontent.com/50475131/249464298-79f8925c-5323-42a4-9807-e0ea9eb0c29d.jpg)
and according to https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#ND7HA `#` is used to access list

**Comment by san346596324** [comment] 2023-06-28 12:38
> > 你好@san346596324你没有尝试过不添加`#`，你可以参考docker模板
> > ![泊坞窗](https://user-images.githubusercontent.com/50475131/249464298-79f8925c-5323-42a4-9807-e0ea9eb0c29d.jpg)
> > 并根据https://www.yuque.com/boyan-avfmj/aviatorscript/ugbmqm#ND7HA，`#`用于访问列表

I used this pattern the first time, but this pattern should recognize - in $. start-time as subtraction

**Comment by l646505418** [comment] 2023-06-28 13:55
The root cause of this issue is that for `$.start-time`,Avitor will treat `$` as a variable and `start-time` is its member variables.
So from my perspective, if this response is returned by offcial API, maybe you can change the parseType, if this response is returned by your designed API, maybe you can change the variables names @tomsun28 @san346596324

**Comment by san346596324** [comment] 2023-06-29 01:01
> The root cause of this issue is that for `$.start-time`,Avitor will treat `$` as a variable and `start-time` is its member variables. So from my perspective, if this response is returned by offcial API, maybe you can change the parseType, if this response is returned by your designed API, maybe you can change the variables names @tomsun28 @san346596324

This is the official API provided by flink. I can't modify it, but from the template point of view, as long as there are fields containing - in the calculates, it should not work properly. I tried parseType: default, but it seems that it cannot parse the array

**Comment by l646505418** [comment] 2023-06-29 15:07
> The root cause of this issue is that for `$.start-time`,Avitor will treat `$` as a variable and `start-time` is its member variables. So from my perspective, if this response is returned by offcial API, maybe you can change the parseType, if this response is returned by your designed API, maybe you can change the variables names @tomsun28 @san346596324

I made a mistake ,the root cause of this issue is not this, the Avitor treats the variable rightly 😂,  I will reproduce the issue and debug it to fix issue tomorrow

**Comment by l646505418** [comment] 2023-06-29 15:20
Hi @san346596324 , would you mind providing the full yml file of the monitor? You can replace the sensative data with "" or "test"

**Comment by tomsun28** [comment] 2023-06-29 15:21
👍

**Comment by san346596324** [comment] 2023-06-29 16:33
> Hi @san346596324 , would you mind providing the full yml file of the monitor? You can replace the sensitive data with "" or "test"
ok
[flink.txt](https://github.com/dromara/hertzbeat/files/11908216/flink.txt)

**Comment by san346596324** [comment] 2023-06-29 16:35
> Hi @san346596324 , would you mind providing the full yml file of the monitor? You can replace the sensitive data with "" or "test"

ok,Can you modify it's format
[flink.txt](https://github.com/dromara/hertzbeat/files/11908231/flink.txt)

**Comment by l646505418** [comment] 2023-06-30 12:39
Hi @tomsun28 @san346596324 , I found that the root cause of this issue is because YAML treats `#` as slash-slash comment， and YAML will not parse this part

![yml](https://github.com/dromara/hertzbeat/assets/50475131/890191aa-e3cc-4acd-81ed-b2c84fd2b59f)


 the `$.start-time - $.last-modification` was commented out...

**Comment by san346596324** [comment] 2023-06-30 13:03
> Hi @tomsun28 @san346596324 , I found that the root cause of this issue is because YAML treats `#` as slash-slash comment， and YAML will not parse this part
> 
> ![yml](https://user-images.githubusercontent.com/50475131/250090046-890191aa-e3cc-4acd-81ed-b2c84fd2b59f.jpg)
> 
> the `$.start-time - $.last-modification` was commented out...

But when you only use $. start-time, this data is also incorrect, not when using # ` `
![1688130037805](https://github.com/dromara/hertzbeat/assets/30828520/0059e8a6-7409-46a9-924e-89e1f5736235)
![image](https://github.com/dromara/hertzbeat/assets/30828520/74b0274c-228c-4218-ac17-f0f1e5da6a4a)

**Comment by l646505418** [comment] 2023-06-30 13:06
Yes, I will do some enhancements at backend code and after that you can use `\#` instead of `#`

![yml](https://github.com/dromara/hertzbeat/assets/50475131/6c0284b4-6202-4377-9f81-2a64e1ce6eb2)

**Comment by san346596324** [comment] 2023-06-30 13:25
> 



> 是的,我会做一些后端代码的改进,然后你可以使用`\#` 代替`#`
> 
> ![YML](https://user-images.githubusercontent.com/50475131/250095965-6c0284b4-6202-4377-9f81-2a64e1ce6eb2.jpg) @san346596324



> Yes, I will do some enhancements at backend code and after that you can use `\#` instead of `#`
> 
> ![yml](https://user-images.githubusercontent.com/50475131/250095965-6c0284b4-6202-4377-9f81-2a64e1ce6eb2.jpg) @san346596324

I tried it and still couldn't help it. If your backend code improvement is complete, please let me know and I will try again

**Comment by l646505418** [comment] 2023-06-30 14:17
> 

Sure, I will inform you after the codes are merged

**Comment by l646505418** [comment] 2023-06-30 14:17
> > 
> 
> > 是的,我会做一些后端代码的改进,然后你可以使用`\#` 代替`#`
> > ![YML](https://user-images.githubusercontent.com/50475131/250095965-6c0284b4-6202-4377-9f81-2a64e1ce6eb2.jpg) @san346596324
> 
> > Yes, I will do some enhancements at backend code and after that you can use `\#` instead of `#`
> > ![yml](https://user-images.githubusercontent.com/50475131/250095965-6c0284b4-6202-4377-9f81-2a64e1ce6eb2.jpg) @san346596324
> 
> I tried it and still couldn't help it. If your backend code improvement is complete, please let me know and I will try again

Sure, I will inform you after the codes are merged

**Closed** 2023-06-30 15:21 UTC
Labels: bug, good first issue, help wanted
